services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:head-alpine
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9005:9005"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server

volumes:
  clickhouse_data:
  clickhouse_log:
